
on:
  push:
    branches:
      - main







jobs:
  build:
    runs-on: ubuntu-latest


    steps:   
      - uses: actions\checkout@v4 

      - name: "docker hub login"
        run: docker login --username alihaamed17 --password ${{ secrets.DOCKER_PAT }}
      - name: Build and push image
        run: |
          docker build -t alihaamed17/AliHamed .
          docker push alihaamed17/AliHamed  
    

